<a href="https://colab.research.google.com/github/ajisakti554/Pemograman-lanjut/blob/main/PraktikumMatriks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**🖥️👩🏻‍💻PRAKTIKUM PEMROGRAMAN LANJUT🔥**
##**Matriks - Senin,  9 DESEMBER 2024**

👤 Nama: Aji Sakti Saputra / NRP: 2C2230012 / Kelas: III/A Sains Data

💬Deskripsi Pembahasan Materi Matriks:






#🤸🏻‍♀️ EKSPLORASI PRIBADI DI KELAS ✨

In [2]:
n= int(input())
m=int(input())
l=int(input())

A=[[0 for j in range(m)]for i in range(n)]
B=[[0 for j in range(l)]for i in range(m)]

for i in range(n):
  for j in range(m):
    A[i][j]=int(input('Masukkan elemen A baris'+str(i+1)+"kolom"+str(j+1)+":"))

    for i in range(m):
      for j in range(l):
        B[i][j]=int(input('Masukkan elemen B baris'+str(i+1)+"kolom"+str(j+1)+":"))




1
2
3
Masukkan elemen A baris1kolom1:1
Masukkan elemen B baris1kolom1:2
Masukkan elemen B baris1kolom2:3
Masukkan elemen B baris1kolom3:3
Masukkan elemen B baris2kolom1:1
Masukkan elemen B baris2kolom2:2
Masukkan elemen B baris2kolom3:3
Masukkan elemen A baris2kolom2:4


IndexError: list index out of range

In [10]:
import numpy as np
x1=np.array([[2,3,4],[2,5,6],[6,7,8]])
x1
x2=np.dot(x1,x1)
x2

array([[ 34,  49,  58],
       [ 50,  73,  86],
       [ 74, 109, 130]])

MATRIKS DENGAN LIST

In [6]:
ls=([2,3,4],[2,5,6],[6,7,8])
ls

([2, 3, 4], [2, 5, 6], [6, 7, 8])

array([[ 34,  49,  58],
       [ 50,  73,  86],
       [ 74, 109, 130]])

#🧠 LATIHAN SOAL DI KELAS ⏱️

NOMOR 1. MEMBUAT SEGITIGA PASCAL

In [11]:
def pascal_triangle(n):
    """Fungsi untuk mencetak segitiga Pascal sederhana hingga n baris."""
    triangle = []  # Menyimpan seluruh segitiga Pascal

    for i in range(n):
        row = [1]  # Baris selalu diawali dengan 1
        if triangle:  # Jika segitiga sudah memiliki baris sebelumnya
            last_row = triangle[-1]
            row.extend([last_row[j] + last_row[j + 1] for j in range(len(last_row) - 1)])
            row.append(1)  # Tambahkan 1 di akhir baris
        triangle.append(row)  # Simpan baris ke segitiga

    # Cetak segitiga Pascal dengan format rapi
    max_width = len(' '.join(map(str, triangle[-1])))
    for row in triangle:
        print(' '.join(map(str, row)).center(max_width))

# Contoh: Mencetak segitiga Pascal dengan 5 baris
pascal_triangle(5)


    1    
   1 1   
  1 2 1  
 1 3 3 1 
1 4 6 4 1


NOMOR DUA LINEAR ALGEBRA

2. Linear Algebra*

Menentukan Determinan dari Matriks
A = [1,2]
    [3,4]

B = [-1,3,0]
    [2,1,-5]
    [1,4,2]

In [12]:
import numpy as np

# Matriks A dan B
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[-1, 3, 0],
              [2, 1, -5],
               [1, 4, -2]])

# Menghitung determinan
det_A = np.linalg.det(A)
det_B = np.linalg.det(B)

print(f"Determinan matriks A: {det_A}")
print(f"Determinan matriks B: {det_B}")



Determinan matriks A: -2.0000000000000004
Determinan matriks B: -21.00000000000001


NOMOR 3

TENTUKAN TRANSPOSE DARI

A=[1 3 7 2]

  [5 8 -9 0]

  [6 -7 11 12]

In [18]:
import numpy as np

# Definisikan matriks A
A = np.array([
    [1, 3, 7, 2],
    [5, 8, -9, 0],
    [6, -7, 11, 12]
])

# Hitung transpose matriks
A_transpose = A.T

print("Matriks A:")
print(A)
print("\nTranspose Matriks A:")
print(A_transpose)

Matriks A:
[[ 1  3  7  2]
 [ 5  8 -9  0]
 [ 6 -7 11 12]]

Transpose Matriks A:
[[ 1  5  6]
 [ 3  8 -7]
 [ 7 -9 11]
 [ 2  0 12]]
